[metadata]
  name = "issue-1337-override-builder-configuration"

[global]
  plan = "integrations"
  case = "issue-1337-override-builder-configuration"
  total_instances = 2
  builder = "docker:go"
  runner = "local:docker"

[[groups]]
  id = "v14"
  instances = { count = 1 }

  [groups.build_config]
    docker_build_image  = "golang:1.14-buster"
    dockerfile_extension = { pre_mod_download = "ENV GOMOD go.v14.mod\nENV GOSUM go.v14.sum" }

  [groups.build]
    selectors = ["v14"]

  [groups.run.test_params]
    expected_version = "v14"

[[groups]]
  id = "v16"
  instances = { count = 1 }

  [groups.build_config]
    docker_build_image  = "golang:1.16-buster"
    dockerfile_extension = { pre_mod_download = "ENV GOMOD go.v16.mod\nENV GOSUM go.v16.sum" }

  [groups.build]
    selectors = ["v16"]

  [groups.run.test_params]
    expected_version = "v16"
