name = "integrations"

[defaults]
builder = "docker:go"
runner = "local:docker"

[builders."docker:go"]
enabled = true
docker_build_image = 'golang:1.v14-buster'
dockerfile_extension = { pre_mod_download = 'ENV GOMOD go.v14.mod\nENV GOSUM go.v14.sum' }

[runners."local:docker"]
enabled = true

[[testcases]]
name = "issue-1337-override-builder-configuration"
instances = { min = 2, max = 2, default = 2 }

[testcases.params]
  expected_version = { type = "string", desc = "expected version" }
