[metadata]
name = "issue-1337-override-builder-configuration"

[global]
builder = "docker:go"
case = "issue-1337-override-builder-configuration"
plan = "integrations"
runner = "local:docker"
total_instances = 2

  [global.build_config]
  docker_build_image = "golang:1.16-buster"
  dockerfile_extensions = {pre_mod_download = "ENV GOMOD go.mod\nENV GOSUM go.sum"}

  [global.build]
  selectors = ["v16"]

[[groups]]
id = "v16"
instances = {count = 1}

  [groups.build]
  selectors = ["v16"]

  [groups.run.test_params]
  expected_version = "v16"

[[groups]]
id = "v14"
instances = {count = 1}

  [groups.build_config]
  docker_build_image = "golang:1.14-buster"
  dockerfile_extensions = {pre_mod_download = "ENV GOMOD go.v14.mod\nENV GOSUM go.v14.sum"}

  [groups.build]
  selectors = ["v14"]

  [groups.run.test_params]
  expected_version = "v14"
